// 账户部分
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

// 单词本部分
export const RECEIVE_WORDBOOK_LIST = 'RECEIVE_WORDBOOK_LIST';
export const RECEIVE_WORDBOOK = 'RECEIVE_WORDBOOK';
