import '../includes.dart';

List<SliceExample> _sliceExamples = [
  SliceAlertDialog(),
  SliceAlign(),
  SliceAnimatedAlign(),
  SliceAnimatedBuilder(),
  SliceAnimatedContainer(),
  SliceAnimatedCrossFade(),
  SliceAnimatedDefaultTextStyle(),
  SliceAnimatedList(),
  SliceAnimatedOpacity(),
  SliceAnimatedPadding(),
  SliceAnimatedPhysicalModel(),
  SliceAnimatedPositioned(),
  SliceAnimatedSize(),
  SliceAnimatedSwitcher(),
  SliceAppBar(),
  SliceAspectRatio(),
  SliceBackdropFilter(),
  SliceBanner(),
  SliceBaseline(),
  SliceBottomAppBar(),
  SliceBottomNavigationBar(),
  SliceBottomSheet(),
  SliceCard(),
  SliceCenter(),
  SliceCheckbox(),
  SliceCheckboxListTile(),
  SliceChip(),
  SliceCircleAvatar(),
  SliceCircularProgressIndicator(),
  SliceClipOval(),
  SliceClipPath(),
  SliceClipRRect(),
  SliceClipRect(),
  SliceColumn(),
  SliceConstrainedBox(),
  SliceContainer(),
  SliceCupertinoActionSheet(),
  SliceCupertinoActivityIndicator(),
  SliceCupertinoButton(),
  SliceCupertinoNavigationBar(),
  SliceCupertinoPageScaffold(),
  SliceCustomPaint(),
  SliceCustomScrollView(),
  SliceDataTable(),
  SliceDatePicker(),
  SliceDecoratedBox(),
  SliceDecoratedBoxTransition(),
  SliceDefaultTextStyle(),
  SliceDismissible(),
  SliceDivider(),
  SliceDraggable(),
  SliceDrawer(),
  SliceDropdownButton(),
  SliceExpanded(),
  SliceExpansionPanelList(),
  SliceFlatButton(),
  SliceFloatingActionButton(),
  SliceFlow(),
  SliceFlutterLogo(),
  SliceForm(),
  SliceGestureDetector(),
  SliceGridView(),
  SliceIcon(),
  SliceIconButton(),
  SliceImage(),
  SliceIndexedStack(),
  SliceInkWell(),
  SliceLinearProgressIndicator(),
  SliceListTile(),
  SliceListView(),
  SliceNestedScrollView(),
  SliceOpacity(),
  SliceOutlineButton(),
  SliceOverflowBox(),
  SlicePadding(),
  SlicePageView(),
  SlicePhysicalModel(),
  SlicePlaceholder(),
  SlicePopupMenuButton(),
  SlicePositioned(),
  SlicePositionedTransition(),
  SliceRadio(),
  SliceRadioListTile(),
  SliceRaisedButton(),
  SliceRefreshIndicator(),
  SliceRichText(),
  SliceRotatedBox(),
  SliceRotationTransition(),
  SliceRow(),
  SliceScaffold(),
  SliceScrollbar(),
  SliceSimpleDialog(),
  SliceSingleChildScrollView(),
  SliceSizedBox(),
  SliceSizedOverflowBox(),
  SliceSlider(),
  SliceSliverAppBar(),
  SliceStack(),
  SliceStepper(),
  SliceSwitch(),
  SliceTabBar(),
  SliceTable(),
  SliceText(),
  SliceTextField(),
  SliceTimePicker(),
  SliceTooltip(),
  SliceTransform(),
  SliceVerticalDivider(),
  SliceWrap(),
];

class _PageExamplePageRoute {}
class _SliceExamplePageRoute {
  SliceExample example;

  String routeName;
  WidgetBuilder buildRoute;

  _SliceExamplePageRoute(this.example) {
    this.routeName = this.example.name ?? this.example.runtimeType.toString();
    this.buildRoute = (_) => Preview4SliceExamplePage(this.example);
  }
}

List<_PageExamplePageRoute> _pageExampleRoutes = [];
List<_SliceExamplePageRoute> _sliceExampleRoutes = []
  ..addAll(_sliceExamples.map((v) => _SliceExamplePageRoute(v)));

List<dynamic> routes = []
  ..addAll(_pageExampleRoutes)
  ..addAll(_sliceExampleRoutes);
